# Generated by Django 5.1.3 on 2024-11-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='permissions',
        ),
        migrations.CreateModel(
            name='DivisionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_post', to='api.division')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_division', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='api.permissions')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_permissions', to='api.post')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='post',
            field=models.ManyToManyField(related_name='divisions', through='api.DivisionPost', to='api.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', through='api.PostPermissions', to='api.permissions'),
        ),
    ]
