# Generated by Django 5.1.3 on 2024-11-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_division_post_remove_post_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='post',
            new_name='posts',
        ),
    ]
