# Generated by Django 5.1.3 on 2024-11-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_permission_postpermissions_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_post', to='api.employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_employee', to='api.post')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ManyToManyField(related_name='employees', through='api.EmployeePost', to='api.post'),
        ),
    ]
