# Generated by Django 5.1.3 on 2024-11-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_employeepost_employee_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='posts',
        ),
        migrations.AddField(
            model_name='division',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='api.division'),
        ),
    ]
