# Generated by Django 5.1.3 on 2024-11-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_post_employee_posts_division_subdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='subdivision',
        ),
        migrations.AddField(
            model_name='division',
            name='main_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_divisions', to='api.division'),
        ),
    ]
